"""learner digital twin

Revision ID: da282b692c5d
Revises: 4df6e492bfb3
Create Date: 2026-08-24 11:00:37.092761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da282b692c5d'
down_revision: Union[str, None] = '4df6e492bfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_domain'), 'concepts', ['domain'], unique=False)
    op.create_index(op.f('ix_concepts_org_id'), 'concepts', ['org_id'], unique=False)
    op.create_index(op.f('ix_concepts_slug'), 'concepts', ['slug'], unique=True)
    op.create_table('concept_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('src_id', sa.String(length=36), nullable=False),
    sa.Column('dst_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_id', 'dst_id', 'relation', name='uq_concept_edge')
    )
    op.create_index(op.f('ix_concept_edges_dst_id'), 'concept_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_concept_edges_src_id'), 'concept_edges', ['src_id'], unique=False)
    op.create_table('learner_concept_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_learner_concept_state')
    )
    op.create_index(op.f('ix_learner_concept_states_concept_id'), 'learner_concept_states', ['concept_id'], unique=False)
    op.create_index(op.f('ix_learner_concept_states_user_id'), 'learner_concept_states', ['user_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misconceptions_concept_id'), 'misconceptions', ['concept_id'], unique=False)
    op.create_table('learner_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('correctness', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('misconception_id', sa.String(length=36), nullable=True),
    sa.Column('source_turn_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_events_concept_id'), 'learner_events', ['concept_id'], unique=False)
    op.create_index(op.f('ix_learner_events_source_turn_id'), 'learner_events', ['source_turn_id'], unique=False)
    op.create_index(op.f('ix_learner_events_user_id'), 'learner_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_events_user_id'), table_name='learner_events')
    op.drop_index(op.f('ix_learner_events_source_turn_id'), table_name='learner_events')
    op.drop_index(op.f('ix_learner_events_concept_id'), table_name='learner_events')
    op.drop_table('learner_events')
    op.drop_index(op.f('ix_misconceptions_concept_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_learner_concept_states_user_id'), table_name='learner_concept_states')
    op.drop_index(op.f('ix_learner_concept_states_concept_id'), table_name='learner_concept_states')
    op.drop_table('learner_concept_states')
    op.drop_index(op.f('ix_concept_edges_src_id'), table_name='concept_edges')
    op.drop_index(op.f('ix_concept_edges_dst_id'), table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_concepts_slug'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_org_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_domain'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
